service: lambda-usuario
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'sa-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:sa-east-1:525067616189:table/USUARIO
      

  memorySize: 128
  timeout: 3  
functions:
  listarTodos:
    handler: handler.listarTodos
    events:
      - httpApi:
         path: /lista/{cpf_cnpj}
         method: get
  consultaPaginada:
    handler: handler.consultaPaginada
    events:
      - httpApi:
         path: /consultaPaginada
         method: post
  listarPorLogin:
    handler: handler.listarPorLogin
    events:
      - httpApi:
         path: /listarPorLogin/{cpf_cnpj}/{login}
         method: get
  efetuarLogin:
    handler: handler.efetuarLogin
    events:
      - httpApi:
         path: /efetuarLogin/{cpf_cnpj}/{chave}
         method: get
  buscaContagem:
    handler: handler.buscaContagem
    events:
      - httpApi:
         path: /buscaContagem/{cpf_cnpj}
         method: get
		   
  cadastrarUsuario:
    handler: handler.cadastrarUsuario
    events:
      - httpApi:
         path: /cadastrarUsuario
         method: post
resources:
  Resources:
    ListaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: USUARIO
        AttributeDefinitions:
          - AttributeName: chave
            AttributeType: S
          - AttributeName: cpf_cnpj
            AttributeType: S
        KeySchema:
          - AttributeName: cpf_cnpj
            KeyType: HASH
          - AttributeName: chave
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1