service: lambda-baixa
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'sa-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:sa-east-1:525067616189:table/BAIXA
      

  memorySize: 128
  timeout: 3  
functions:
  listaSinteticaBaixa:
    handler: handler.listaSinteticaBaixa
    events:
      - httpApi:
         path: /listaSinteticaBaixa/{cpf_cnpj}/{chave}
         method: get
  cadastrarBaixa:
    handler: handler.cadastrarBaixa
    events:
      - httpApi:
         path: /cadastrarBaixa
         method: post
  listaAnaliticaBaixa:
    handler: handler.listaAnaliticaBaixa
    events:
      - httpApi:
         path: /listaAnaliticaBaixa/{cpf_cnpj}/{chave}
         method: get
 
resources:
  Resources:
    ListaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BAIXA
        AttributeDefinitions:
          - AttributeName: chave
            AttributeType: S
          - AttributeName: cpf_cnpj
            AttributeType: S
        KeySchema:
          - AttributeName: cpf_cnpj
            KeyType: HASH
          - AttributeName: chave
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1