service: lambda-relatorio
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'sa-east-1'}
      
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:sa-east-1:525067616189:table/*
   
  memorySize: 256
  timeout: 3 
functions:
  relEstoque:
    handler: handler.relEstoque
    events:
      - httpApi:
         path: /relEstoque/{cpf_cnpj}/{chave}
         method: get
