service: lambda-unidades
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'sa-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:sa-east-1:525067616189:table/UNID_VENDA
      

  memorySize: 128
  timeout: 3  
functions:
  listarTodas:
    handler: handler.listarTodas
    events:
      - httpApi:
         path: /lista/{cpf_cnpj}
         method: get
  scanTable:
    handler: handler.scanTable
    events:
      - httpApi:
         path: /scanTable/{cpf_cnpj}
         method: get
  unidadePorId:
    handler: handler.unidadePorId
    events:
      - httpApi:
         path: /unidadeporid/{cpf_cnpj}/{idUnidade}
         method: get
  consultaPaginada:
    handler: handler.consultaPaginada
    events:
      - httpApi:
         path: /consultaPaginada
         method: post
  buscaContagem:
    handler: handler.buscaContagem
    events:
      - httpApi:
         path: /buscaContagem/{cpf_cnpj}
         method: get 
  cadastrarUnidade:
    handler: handler.cadastrarUnidade
    events:
      - httpApi:
         path: /cadastrarUnidade
         method: post
resources:
  Resources:
    ListaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UNID_VENDA
        AttributeDefinitions:
          - AttributeName: idUnidade
            AttributeType: S
          - AttributeName: cpf_cnpj
            AttributeType: S
        KeySchema:
          - AttributeName: cpf_cnpj
            KeyType: HASH
          - AttributeName: idUnidade
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1