service: lambda-estoque
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'sa-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:sa-east-1:525067616189:table/APORTE
      

  memorySize: 128
  timeout: 3  
functions:
  cadastrarAporte:
    handler: handler.cadastrarAporte
    events:
      - httpApi:
         path: /cadastrarAporte
         method: post
  
resources:
  Resources:
    ListaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: APORTE
        AttributeDefinitions:
          - AttributeName: chave
            AttributeType: S
          - AttributeName: cpf_cnpj
            AttributeType: S
        KeySchema:
          - AttributeName: cpf_cnpj
            KeyType: HASH
          - AttributeName: chave
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1