service: lambda-estoque-geral
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'sa-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
      Resource: "*"
      

  memorySize: 128
  timeout: 3 
functions:
  consultaEstoqueGeral:
    handler: handler.consultaEstoqueGeral
    events:
      - httpApi:
         path: /consultaEstoqueGeral/{cpf_cnpj}/{idProduto}
         method: get
 
